<?php
/**
 * Ajax
 */

function clampdown_codes_ajax_add_code() {
  extract($_POST);
  global $clampdownCodesQuery;
  $result = $clampdownCodesQuery->addCode($code, $group);

  if(is_numeric($result)) {
    wp_send_json([
      'successfull' => true,
      'message' => sprintf('%s %s (#%s)', $code, __('added successfully', 'cgc'), $result),
      'entry' => $clampdownCodesQuery->getCode($code),
    ]);
  } else {
    wp_send_json([
      'successfull' => false,
      'message' => isset($result['message']) ? $result['message'] : __('Insert code error.'),
    ]);
  }
}

add_action('wp_ajax_clampdown_codes_ajax_add_code', 'clampdown_codes_ajax_add_code');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_add_code', 'clampdown_codes_ajax_add_code');

function clampdown_codes_ajax_get_codes() {
  extract($_POST);
  global $clampdownCodesQuery;
  wp_send_json($clampdownCodesQuery->getCodes($paged, -1));
}

add_action('wp_ajax_clampdown_codes_ajax_get_codes', 'clampdown_codes_ajax_get_codes');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_get_codes', 'clampdown_codes_ajax_get_codes');

function clampdown_codes_ajax_delete_codes() {
  extract($_POST);
  global $clampdownCodesQuery;
  $clampdownCodesQuery->deleteCodes(explode(',', $codes));

  wp_send_json([
    'successfull' => true,
    'message' => sprintf('%s', __('Delete successfully.', 'cgc')),
  ]);
}

add_action('wp_ajax_clampdown_codes_ajax_delete_codes', 'clampdown_codes_ajax_delete_codes');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_delete_codes', 'clampdown_codes_ajax_delete_codes');

function clampdown_codes_ajax_auto_generate_codes() {
  extract($_POST);
  global $clampdownCodesQuery;
  $clampdownCodesQuery->autoGenerateCodes($number, $group);

  wp_send_json([
    'successfull' => true,
    'message' => sprintf('%s', __('Auto generate successfully.', 'cgc')),
  ]);
}

add_action('wp_ajax_clampdown_codes_ajax_auto_generate_codes', 'clampdown_codes_ajax_auto_generate_codes');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_auto_generate_codes', 'clampdown_codes_ajax_auto_generate_codes');

function clampdown_codes_ajax_get_download_config() {
  wp_send_json(clampdown_codes_get_download_config());
}

add_action('wp_ajax_clampdown_codes_ajax_get_download_config', 'clampdown_codes_ajax_get_download_config');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_get_download_config', 'clampdown_codes_ajax_get_download_config');

function clampdown_codes_ajax_update_download_config() {
  wp_send_json(clampdown_codes_update_download_config($_POST));
}

add_action('wp_ajax_clampdown_codes_ajax_update_download_config', 'clampdown_codes_ajax_update_download_config');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_update_download_config', 'clampdown_codes_ajax_update_download_config');

function clampdown_codes_ajax_validate() {
  extract($_POST);
  $result = clampdown_codes_validate_progress($data['code'], $data['group']);
  wp_send_json($result);
}

add_action('wp_ajax_clampdown_codes_ajax_validate', 'clampdown_codes_ajax_validate');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_validate', 'clampdown_codes_ajax_validate');

function clampdown_codes_ajax_upload_file_import() {
  if (!function_exists('wp_handle_upload')) {
    require_once(ABSPATH . 'wp-admin/includes/file.php');
  }

  $uploadedfile = $_FILES['file'];
  $upload_overrides = ['test_form' => false];
  $movefile = wp_handle_upload($uploadedfile, $upload_overrides);
  
  if ($movefile && ! isset($movefile['error'])) {
    $json = clampdown_codes_read_csv_file_to_json($movefile['file']);
    wp_send_json([
      'successful' => true,
      'message' => __('File is valid, and was successfully uploaded.', 'cgc'),
      'result' => $movefile,
      'entry' => json_decode($json, true)
    ]);
  } else {
    /*
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    wp_send_json([
      'successful' => false,
      'message' => $movefile['error'],
    ]);
  }
}

add_action('wp_ajax_clampdown_codes_ajax_upload_file_import', 'clampdown_codes_ajax_upload_file_import');
add_action('wp_ajax_nopriv_clampdown_codes_ajax_upload_file_import', 'clampdown_codes_ajax_upload_file_import');